### ISSUE TITLE
Network Vertex Metrics Visualizer - Names of files

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#10]
In the Network Vertex Metrics Visualizer Shiny app, currently histograms are titled:

Histogram of file 1
Histogram of file 2
Histogram of file 3
...

Can we change the titles as:

Histogram for <name of file 1>
Histogram for <name of file 2>
Histogram for <name of file 3>
...

**Comment by manishjain2792** [comment]
You mean to say "Histogram for filename "  ?

**Comment by dsubhaji** [comment]
Exactly! Sorry for the slip ...

The titles are to be:

Histogram for <file-name 1>
Histogram for <file-name 2>
Histogram for <file-name 3>
....

**Comment by manishjain2792** [comment]
Sir. Done..

**Comment by dsubhaji** [comment]
Checked and closed!
