### ISSUE TITLE
Network_family_metrics_visualizer - heading plus plot title

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#11]
In the Shiny app for Network_family_metrics_visualizer the title says "Network Family Metrics calculator"; this should be "Network Family Metrics Visualizer".  Also, all the plots are titled as "Line plot of file 1". Let us call them "Line plot of Degree Centrality", "Line plot of Diameter" etc

**Comment by manishjain2792** [comment]
Done Sir.

**Comment by dsubhaji** [comment]
See my mail.

**Comment by manishjain2792** [comment]
Sir, please find the attachment as I am not getting any error.  Please
synchronise the latest code (both server.R and ui.R) in your local
workspace.

Regards,
Manish

**Comment by dsubhaji** [comment]
Thanks!
