### ISSUE TITLE
New metrcis for Network_family_metrics_calculator.R

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#12]
We will enhance the metrics we calculate for network families with the following:
1. Rename degree as degree-centralization
2. Calculate betweenness-centralization 
3. Calculate closeness-centralization
4. Calculate eigenvector-centralization 
5. Rename clustcoeff as global-clustcoeff 
6. Calculate assortativity  
7. Keep diameter unchanged
8. Keep density unchanged
9. Keep modularity  unchanged
10. Keep avg-path-length unchanged
11. Keep avg-degree unchanged

**Comment by manishjain2792** [comment]
Sir, I have modified the code and also the shiny app. Please synchronize the code as well as the shiny app  for family metrics visualization.

**Comment by dsubhaji** [comment]
Thanks!
