### ISSUE TITLE
 Cannot read Pajek file

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#5]
I am getting the following error. I am attaching the folder contents by email.

Enter The Folder Location: C:\Users<user-id>\Desktop\test-R-one
Select the metrics you want to calculate (space-separated list) 

1.Degree
2.Betweenness
3.Clustering Coeff
4.Closeness
5.Eigen Centrality
6.PageRank 
1 2
Error in .Call("R_igraph_read_graph_pajek", file, PACKAGE = "igraph") : 
  At rinterface.c:5059 : Cannot read Pajek file, File operation error

**Comment by manishjain2792** [comment]
Sir , while giving the input path please give a back slash at the end , so the input path location will be-

Enter The Folder Location: C:\Users<user-id>\Desktop\test-R-one\

or

Enter The Folder Location: C:/Users<user-id>/Desktop/test-R-one/
