### ISSUE TITLE
NA fields

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#6]
Whenever any "NA" is generated in computing network metrics (single network or network families), set it to "0" (zero).

**Comment by manishjain2792** [comment]
I have fixed the bug. Please check and let me know.

**Comment by dsubhaji** [comment]
Look at the mail I sent with a sample input file.

**Comment by manishjain2792** [comment]
Sir. It is fixed. Check it.

**Comment by dsubhaji** [comment]
Checked and closed!
