### ISSUE TITLE
Handling directed networks

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-analysis#8]
Network_vertex_metrics_calculator.R and Network_family_metrics_calculator.R needs to be able to handle directed networks. Have a checkbox where the user can enter whether the network is directed or not. For directed networks in addition to "degree" there needs to be a "in-degree" and "out-degree" calculated for each vertex (degree = in-degree + out-degree). Check how the other metrics are calculated for directed networks and change the code accordingly.

**Comment by manishjain2792** [comment]
Fixed for directed as well as undirected.

**Comment by manishjain2792** [comment]
added the in degree and out degree column for directed networks.

**Comment by dsubhaji** [comment]
Thanks!
